---
lamp::mysql_root_user: "root"
lamp::mysql_root_password: ";dslagku*(PDSGDS"

epcc::database_root_user: "root"
epcc::database_root_password: ";dslagku*(PDSGDS"

epcc::database_name: "EclipsePhaseData"
epcc::database_user: "epcc_www"
epcc::database_password: "0928sdGdsfa8#_+"
epcc::database_sql_file: "/mnt/epcc/sql/FullDatabase.sql"